version: "2"

checks:
  complex-logic:
    config:
      threshold: 10
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 30

plugins:
  brakeman:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-49
