image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  IMAGE_PREFIX: $CI_REGISTRY_IMAGE/ci
services:
- docker:dind

before_script:
- docker info

build:
  stage: build
  only:
    - ci
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $IMAGE_PREFIX:$CI_COMMIT_SHA -t $IMAGE_PREFIX:latest .
  - docker push $IMAGE_PREFIX:$CI_COMMIT_SHA
  - docker push $IMAGE_PREFIX:latest
